### ISSUE TITLE
32位win7系统无法运行1.0及之后的任何版本

### ISSUE THREAD

**Issue by kouhai114** [Horiztar/Cylheim-Windows#5]
装了32位5.0.3版本的运行环境，1.0到1.0.3版本会提示停止运行，1.0.4版本的错误报告：
向类型为“System.Windows.Controls.UIElementCollection”的集合中添加值引发了异常。
at Column 0, Line 0, 

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Cylheim.MainWindow.InitializeComponent()
   at Cylheim.MainWindow..ctor()
   at Cylheim.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
求作者解决orz

**Comment by Horiztar** [comment]
您使用的是什么系统？系统是32位还是64位？

**Comment by Horiztar** [comment]
如果您愿意，麻烦加入 QQ 群 694808508 进一步提供信息来协助解决。
