### ISSUE TITLE
Error code whenever I press play in Cylheim

### ISSUE THREAD

**Issue by mr-gage** [Horiztar/Cylheim-Windows#9]
Hi all,

I'm getting this error code whenever I hit play in Cylheim:

Cannot create a KeyTime with the value '-00:00:02' because it is less than zero. (Parameter 'timeSpan')
at System.Windows.Media.Animation.KeyTime.FromTimeSpan(TimeSpan timeSpan) in PresentationCore.dll:token 0x6002fc7+0x30
at Cylheim.Animation.AnimateUtil.AddFrame[TKeyFrame](IKeyFrameAnimation animation, Object value, Double time) in C:\Users\horiz\source\repos\Horiztar\Cylheim\Cylheim\Animation\AnimateUtil.cs:line 40
at Cylheim.Animation.FrameAnimationNote.AddEnterAnimation(Note note) in C:\Users\horiz\source\repos\Horiztar\Cylheim\Cylheim\Animation\FrameAnimationNote.xaml.cs:line 212
at Cylheim.ChartEditor.EditorPanel.InitNoteAnimation() in C:\Users\horiz\source\repos\Horiztar\Cylheim\Cylheim\ChartEditor\EditorPanel_Player.cs:line 421
at Cylheim.ChartEditor.EditorPanel.InitStoryboard() in C:\Users\horiz\source\repos\Horiztar\Cylheim\Cylheim\ChartEditor\EditorPanel_Player.cs:line 255
at Cylheim.ChartEditor.EditorPanel.Play(Nullable`1 time, Boolean init) in C:\Users\horiz\source\repos\Horiztar\Cylheim\Cylheim\ChartEditor\EditorPanel_Player.cs:line 123
at Cylheim.MainViewModel.<get_PlayCommand>b__28_0(Object arg) in C:\Users\horiz\source\repos\Horiztar\Cylheim\Cylheim\MainPagePlayer.cs:line 115
at Cylheim.UI.RelayCommand.Execute(Object parameter) in C:\Users\horiz\source\repos\Horiztar\Cylheim\Cylheim\UI\RelayCommand.cs:line 42
at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated) in PresentationFramework.dll:token 0x60017f7+0x4a
at System.Windows.Controls.Primitives.ButtonBase.OnClick() in PresentationFramework.dll:token 0x6007992+0x13
at System.Windows.Controls.Button.OnClick() in PresentationFramework.dll:token 0x6006002+0x1a
at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e) in PresentationFramework.dll:token 0x60079b0+0x44
at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e) in PresentationCore.dll:token 0x60006c3+0x43
at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget) in PresentationCore.dll:token 0x6000c58+0x0
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) in PresentationCore.dll:token 0x6000b6a+0x19
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) in PresentationCore.dll:token 0x6000c39+0x20e
at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent) in PresentationCore.dll:token 0x600085e+0xbf
at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e) in PresentationCore.dll:token 0x60006bf+0x46
at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget) in PresentationCore.dll:token 0x6000c58+0x0
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) in PresentationCore.dll:token 0x6000b6a+0x19
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) in PresentationCore.dll:token 0x6000c39+0x20e
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) in PresentationCore.dll:token 0x600085f+0xaf
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args) in PresentationCore.dll:token 0x60006ad+0xd
at System.Windows.Input.InputManager.ProcessStagingArea() in PresentationCore.dll:token 0x6000c27+0x0
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input) in PresentationCore.dll:token 0x6000c1e+0xd
at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport) in PresentationCore.dll:token 0x6003169+0x0
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel) in PresentationCore.dll:token 0x6003931+0x0
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in PresentationCore.dll:token 0x600392b+0x5b7
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in PresentationCore.dll:token 0x600039b+0xd2
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in WindowsBase.dll:token 0x60001a3+0x99
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) in WindowsBase.dll:token 0x6000193+0x60
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) in WindowsBase.dll:token 0x6000eb4+0xca
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) in WindowsBase.dll:token 0x6000eb3+0x3a

I can't figure out how to rectify this. Any thoughts?

Thank you, Nathan

**Comment by Horiztar** [comment]
Please provide the chart (or the segment of chart) caused this error.
